<section>
    <h2>Dashboard</h2>

    <nav>
        <a class="btn" href="<?=buildUrl('user_picture_new');?>"><i class="fas fa-plus-square"></i> Ajouter un article</a>
    </nav>

    <table> 
        <thead>
            <th>#</th>
            <th>Date de création</th>
            <th>nom</th>
            <th>descritpion</th>
            <th>Actions</th>
        </thead>
        <tbody>
            <?php foreach ($pictures as $picture): ?>
                <tr id="article-<?=$picture['pictureId']?>">
                    <td><?=intval($picture['pictureId']);?></td>
                    <td><?=(new DateTimeImmutable($picture['createdAt']))->format('d/m/Y');?></td>
                    <td><?=$picture['namePicture']?></td>
                    <td><?=htmlspecialchars($article['descriptionPicture']);?></td>
                    <td>
                        
                            <a href="<?=buildUrl('admin_article_edit', ['article_id' => $article['article_id']]);?>" title="Modifier"><i class="far fa-edit"></i></a>
                       
                            <a href="<?=buildUrl('admin_article_delete', ['article_id' => $article['article_id']]);?>" title="supprimer" class ="delete-button"><i class="far fa-trash-alt"></i></a>
                        
                        
                      
                        
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    
</section>
<script src="<?=asset('js/admin.js');?>"></script>