<?php 
use App\Framework\UserSession;
?>

<?php
 include VIEW_DIR ."/header.phtml";
?>
<aside class="message">
            <?php if (App\Framework\FlashBag::hasMessages('error')):?>
                <?php foreach (App\Framework\FlashBag::fetchMessages('error') as $error):?>
                    <p class="message error-message"><?=htmlspecialchars($error);?></p>
                <?php endforeach; ?>
            <?php endif; ?>

            <?php if (App\Framework\FlashBag::hasMessages('success')):?>
                <?php foreach (App\Framework\FlashBag::fetchMessages('success') as $message):?>
                    <p class="message success-message"><?=htmlspecialchars($message);?></p>
                <?php endforeach; ?>
            <?php endif; ?>
</aside>

<?php include VIEW_DIR ."/".$template.".phtml";?>

<?php include VIEW_DIR ."/footer.phtml"; ?>