




<section class="signup">
    <p class="signup-title">Sign Up</p>
    <form class="signup-form" action="<?=buildUrl('signup');?>" method="POST">
        
            <div class="signup-form-pseudo">
                <label for="pseudo">pseudo</label>
                <input type="text" name="pseudo" id="pseudo" value="<?=$pseudo??"";?>" placeholder="pseudo">
            </div>
            <div class="signup-form-email">
                <label for="email">Email</label>
                <input type="email" name="email" id="email" value="<?=$email;?>" placeholder="email">
            </div>
            <div class="signup-form-password">
                <label for="password">Password</label>
                <input type="password" name="password" id="password" placeholder="password">
            </div>
            <div class="signup-form-repeatPassword">
                <label for="RepeatPassword">Repeat password</label>
                <input type="password" name="RepeatPassword" id="RepeatPassword" placeholder="repeat pasword">
            </div>
            <div id="signup-form-register">

            <input id="signup-form-register-enter" type="submit" value="register">
            </div>
        
    </form>

</section>
