<section>
    <h2>Rédiger un article</h2>
    
    <!-- Route vers laquelle on cree le lien -->
    <form action="<?=buildUrl('admin_article_new');?>" method="post">
        <fieldset>
            <div>
                <label for="title">Titre</label>
                <input type="text" id="title" name="title" value="">
            </div>
            <div>
                <label for="content">Contenu</label>
                <textarea id="content" name="content"></textarea>
            </div>
            <div>
                <label for="category">Catégorie</label>
                <select id="category" name="category">
                    <?php foreach ($categories as $category): ?>
                        <option value="<?=$category['id'];?>"><?=$category['label'];?></option>
                    <?php endforeach; ?>
                </select>
            </div>
        </fieldset>
        <input type="submit" value="Valider">
    </form>
</section>